version: '3'
services:
  node:
    image: node:alpine
    container_name: node
    restart: always
    ports:
      - '3333:3333'

mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - '3333:3333'

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}